# Generated by Django 5.0.1 on 2025-08-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='budget',
            field=models.CharField(blank=True, help_text='Budget range', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='timeline',
            field=models.CharField(blank=True, help_text='Preferred project timeline', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quote Sent'), ('negotiating', 'Negotiating'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
