# Generated by Django 4.2.7 on 2026-01-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_serviceorder_budget_serviceorder_timeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='fas fa-code', help_text='Font Awesome icon class', max_length=100),
        ),
    ]
