# Generated by Django 5.2.5 on 2026-02-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['description'],
            },
        ),
    ]
